<?php

namespace AppBundle\Repository;

/**
 * AlbumGendreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumGendreRepository extends \Doctrine\ORM\EntityRepository
{
}
