<?php

namespace AppBundle\Repository;

/**
 * GendreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GendreRepository extends \Doctrine\ORM\EntityRepository
{
}
