<?php

namespace AppBundle\Repository;

/**
 * PersonAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonAlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
